///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Jenkins_Param
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
          /// <summary>
          /// The class representing the Jenkins_ParamRepository element repository.
          /// </summary>
          [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
          [RepositoryFolder("4ee04ed6-6db7-4f14-910a-cc038802da93")]
          public partial class Jenkins_ParamRepository : RepoGenBaseFolder
          {
                    static Jenkins_ParamRepository instance = new Jenkins_ParamRepository();

                    /// <summary>
                    /// Gets the singleton class instance representing the Jenkins_ParamRepository element repository.
                    /// </summary>
                    [RepositoryFolder("4ee04ed6-6db7-4f14-910a-cc038802da93")]
                    public static Jenkins_ParamRepository Instance
                    {
                              get { return instance; }
                    }

                    /// <summary>
                    /// Repository class constructor.
                    /// </summary>
                    public Jenkins_ParamRepository() 
                              : base("Jenkins_ParamRepository", "/", null, 0, false, "4ee04ed6-6db7-4f14-910a-cc038802da93", ".\\RepositoryImages\\Jenkins_ParamRepository4ee04ed6.rximgres")
                    {
                    }

#region Variables

#endregion

                    /// <summary>
                    /// The Self item info.
                    /// </summary>
                    [RepositoryItemInfo("4ee04ed6-6db7-4f14-910a-cc038802da93")]
                    public virtual RepoItemInfo SelfInfo
                    {
                              get
                              {
                                        return _selfInfo;
                              }
                    }
          }

          /// <summary>
          /// Inner folder classes.
          /// </summary>
          [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
          public partial class Jenkins_ParamRepositoryFolders
          {
          }
#pragma warning restore 0436
}
